import { MenuItem } from './types';

export const menuCategories = [
  { id: 'appetizers', label: 'Appetizers', emoji: '🥟', description: 'Freshly seasoned hot and cold Japanese gourmet starters.' },
  { id: 'soup', label: 'Soup', emoji: '🥣', description: 'Flavorful traditional broths and noodle soups.' },
  { id: 'salad', label: 'Salad', emoji: '🥗', description: 'Crisp green salads, seaweed accompaniments, and seasoned seafood bowls.' },
  { id: 'sushisashimialacarte', label: 'Sushi & Sashimi A La Carte', emoji: '🍣', description: 'A la carte premium raw fish and seafood selections by piece.' },
  { id: 'classicrollandhandroll', label: 'Classic & Hand Rolls', emoji: '🌯', description: 'Traditional rolled seaweed sheets enclosing fresh seafood or veggie choices.' },
  { id: 'signaturerolls', label: 'Signature Rolls', emoji: '🐉', description: 'Chef-inspired premium specialty sushi rolls with high-end toppings.' },
  { id: 'sushibarentrees', label: 'Sushi Bar Entrees', emoji: '🍱', description: 'Curated premium sushi combos, rice bowls, and sashimi assortments.' },
  { id: 'riceandnoodles', label: 'Rice & Noodles', emoji: '🍜', description: 'Sizzling Japanese noodles, Thai staple pad thais, and fried rice selections.' },
  { id: 'kitchenentrees', label: 'Kitchen Entrees & Curry', emoji: '🍛', description: 'Savory glazed teriyaki meats, katsu cutlets, and thick aromatic curries.' },
  { id: 'hibachidinners', label: 'Hibachi Dinners', emoji: '🔥', description: 'Cooked live on the iron grill. Served with soup, salad, vegetables, rice, and gold yum-yum sauce.' },
  { id: 'drinks', label: 'Drinks', emoji: '🍶', description: 'Refreshing premium teas, classic sodas, and imported Japanese waters.' },
  { id: 'dessert', label: 'Dessert', emoji: '🍰', description: 'Sweet endings including fried sweet bananas and premium golden katsu cheesecake.' }
];

export const menuItems: Record<string, MenuItem[]> = {
  appetizers: [
    { id: 'a1', name: 'Edamame', price: 6.50, description: 'Steamed green soybean pods tossed with mineral coarse sea salt.', tags: ['Gluten-Free', 'Vegetarian'] },
    { id: 'a2', name: 'Crab Rangoon', price: 7.50, description: 'Crisp fried wonton pouches loaded with loaded crab meat and sweetened cream cheese filling.', tags: ['Crispy', 'Popular'] },
    { id: 'a3', name: 'Shrimp Shumai', price: 7.00, description: 'Steamed bite-sized round shrimp dumplings paired with a premium vinegar soy dip.', tags: ['Steamed'] },
    { id: 'a4', name: 'Fried Tofu', price: 6.50, description: 'Fried soft tofu blocks served with ground ginger-radish oil and dash sashi dashi.', tags: ['Vegetarian'] },
    { id: 'a5', name: 'Haru Maki', price: 6.00, description: 'Crisp hot Japanese vegetable spring rolls wrapped with sweet chili glaze.', tags: ['Vegetarian', 'Crispy'] },
    { id: 'a6', name: 'Pork Gyoza', price: 7.50, description: 'Pan-fried Japanese dumplings packed with minced seasoned local pork.', tags: ['Dipping Sauce'] },
    { id: 'a7', name: 'Vegetable Gyoza', price: 7.50, description: 'Pan-fried light thin wheat flour wrappers filled with julienned vegetables.', tags: ['Vegetarian'] },
    { id: 'a8', name: 'Tempura Vegetables', price: 8.50, description: 'Thoroughly battered and crisped sweet potato, broccoli, onion, and zucchini slices.', tags: ['Crispy'] },
    { id: 'a9', name: 'Tempura Shrimp and Vegetable', price: 11.50, description: 'Plump premium shrimp battered and served with assorted golden crispy seasonal vegetables.', tags: ['Signature'] },
    { id: 'a10', name: 'Fried Calamari', price: 11.00, description: 'Premium ring cut squid dusted with seasoned pepper salt flour and flashed gold.', tags: ['Crispy'] },
    { id: 'a11', name: 'Tako King', price: 10.50, description: 'Delectable sliced tender octopus medallions served with a splash of sweet vinegar ponzu.', tags: ['Cold Appetizer'] },
    { id: 'a12', name: 'Tuna Tataki', price: 12.50, description: 'Lightly pan-seared red tuna slices with fine black pepper and citrusy dipping sauce.', tags: ['Sashimi Grade'] },
    { id: 'a13', name: 'Spicy Kani Inari', price: 7.50, description: 'Seasoned tofu pouches stuffed with spicy julienned crabmeat and drizzled with sweet unagi glaze.', tags: ['Spicy'] },
    { id: 'a14', name: 'Tokyo Ceviche', price: 13.50, description: 'Assorted raw salmon, tuna, white fish chunks tossed with lime juice, cucumber and avocado.', tags: ['Fresh'] },
    { id: 'a15', name: 'Salmon Tartare', price: 12.50, description: 'Finely minced fresh orange salmon layered over diced avocado, crowned with spicy mayo and tobiko.', tags: ['Gourmet'] },
    { id: 'a16', name: 'Tuna Tartare', price: 12.50, description: 'Chopped sashimi-grade yellowfin tuna combined with custom house spicy herbs.', tags: ['Spicy'] },
    { id: 'a17', name: 'Yellowtail Tartare', price: 13.50, description: 'Minced premium yellowtail paired with scallions, roe, and yuzu soy reduction.', tags: ['Exquisite'] },
    { id: 'a18', name: '5 Tempura Oysters', price: 12.00, description: 'Panko and tempura battered deep sea oysters served golden with katsu dip.', tags: ['Warm Starter'] },
    { id: 'a19', name: 'Agedashi Tofu', price: 7.00, description: 'Gently crisped silken tofu submerged in a bath of savory hot tentsuyu broth.', tags: ['Vegetarian'] },
    { id: 'a20', name: 'Kitchen Thai Fresh Summer', price: 8.00, description: 'Crushed raw mint leaves, shrimp, and vegetables wrapped in a gluten-free rice paper roll.', tags: ['Gluten-Free'] },
    { id: 'a21', name: 'Soft Shell Crab', price: 12.50, description: 'Whole pristine soft shell crab crisped tempura-style, paired with citrusy dipping sauces.', tags: ['Popular'] },
    { id: 'a22', name: 'Yellowtail Carpaccio', price: 13.50, description: 'Thin raw yellowtail ribbons topped with wild sliced jalapenos and ponzu reduction.', tags: ['Spicy', 'Cold Appetizer'] }
  ],
  soup: [
    { id: 'sp1', name: 'Clear Mushroom Soup', price: 3.00, description: 'A light, traditional clear beef broth containing sliced white button mushrooms and sweet fried onions.', tags: ['Lighter Option'] },
    { id: 'sp2', name: 'Miso Soup', price: 3.00, description: 'Classic Japanese soy paste broth featuring soft silken tofu cubes, kombu seaweed, and minced green scallions.', tags: ['Traditional'] },
    { id: 'sp3', name: 'Wonton Dumpling Soup', price: 5.50, description: 'Slightly seasoned clear chicken broth loaded with pillow-soft minced pork wonton wrappers.', tags: ['Hearty'] },
    { id: 'sp4', name: 'Seafood Miso Soup', price: 7.50, description: 'Rich miso paste soup loaded with mussels, shrimp, calamari rings and fresh sea greens.', tags: ['Premium'] },
    { id: 'sp5', name: 'Tom Kha Soup', price: '6.00+', description: 'Warm coconut milk soup combined with galangal root, lemongrass, lime juice, and choosing veggie/chicken option.', tags: ['Thai Classic'] },
    { id: 'sp6', name: 'Tom Yum Soup', price: '6.00+', description: 'Spicy lemongrass broth with mushrooms, fresh tomatoes, coriander, and choice of protein.', tags: ['Spicy'] }
  ],
  salad: [
    { id: 'sl1', name: 'House Salad', price: 4.00, description: 'Crispy iceberg lettuce salad paired with sweet, velvety home-crafted Japanese ginger dressing.', tags: ['Must Order'] },
    { id: 'sl2', name: 'Sesame Seaweed Salad', price: 6.50, description: 'Lightly shredded agar-seaweed ribbons tossed with sesame oil, vinegar, and roasted sesame seeds.', tags: ['Vegetarian'] },
    { id: 'sl3', name: 'Kani Salad', price: 7.50, description: 'Julienned crab sticks, cucumber strips, and crunchy tempura flakes rolled in sweet spicy mayonnaise.', tags: ['Diner Favorite'] },
    { id: 'sl4', name: 'Avocado Garden Salad', price: 7.00, description: 'Gently sliced fresh avocado placed on a bed of crisp greens with house ginger base sauce.', tags: ['Vegetarian'] },
    { id: 'sl5', name: 'Spicy Tuna Salad', price: 9.50, description: 'Sashimi-grade spicy minced red tuna placed over greens, splashed with sriracha spicy mayo.', tags: ['Spicy'] },
    { id: 'sl6', name: 'Salmon Skin Salad', price: 8.50, description: 'Crisply pan-grilled salmon skin chips tossed with baby greens and sweet soy reduction.', tags: ['Crispy'] },
    { id: 'sl7', name: 'Seared Salmon Salad', price: 11.50, description: 'Gently torched buttery salmon slices laid over organic spring mix salad.', tags: ['Premium'] },
    { id: 'sl8', name: 'Crusted Sesame Tuna Salad', price: 12.50, description: 'Seared roasted sesame black-pepper-crusted tuna slices with yuzu vinegar.', tags: ['Chef Special'] }
  ],
  sushisashimialacarte: [
    { id: 'ss1', name: 'Crab Stick (Kani)', price: '5.00+', description: 'Hand-sliced sweet mock crab stick. Available as 2pcs Sushi or 3pcs Sashimi.', tags: ['Classic'] },
    { id: 'ss2', name: 'Egg (Tamago)', price: '5.00+', description: 'Traditional multi-layered sweet baked Japanese egg omelet slices.', tags: ['Sweet'] },
    { id: 'ss3', name: 'Tofu Skin (Inari)', price: '5.00+', description: 'Sweet pockets of soy curd stuffed with seasoned vinegared sushi rice.', tags: ['Vegetarian'] },
    { id: 'ss4', name: 'Tuna (Maguro)', price: '7.00+', description: 'Glistening slices of brilliant red lean sashimi-grade yellowfin tuna.', tags: ['Bestseller'] },
    { id: 'ss5', name: 'White Tuna', price: '7.50+', description: 'Extremely buttery and creamy super white tuna sashimi/sushi slices.', tags: ['Creamy'] },
    { id: 'ss6', name: 'Albacore', price: '7.00+', description: 'Smooth, lightly savory, and elegant long-fin albacore tuna slices.', tags: ['Delicate'] },
    { id: 'ss7', name: 'Squid (Ika)', price: '6.50+', description: 'Glossy ivory ribbons of sweet sliced sashimi squid.', tags: ['Traditional'] },
    { id: 'ss8', name: 'Red Clam (Hokkigai)', price: '6.50+', description: 'Traditional sweet arctic surf clams with vibrant pink or red tips.', tags: ['Sweet'] },
    { id: 'ss9', name: 'Salmon (Sake)', price: '7.00+', description: 'Richly marbled coral-pink fresh raw Atlantic salmon slices.', tags: ['Most Popular'] },
    { id: 'ss10', name: 'Smoked Salmon', price: '7.50+', description: 'Elegantly salt-cured and hickory-smoked custom salmon slices.', tags: ['Savory'] },
    { id: 'ss11', name: 'Spicy Tuna', price: '7.50+', description: 'Tender tuna sashimi chunks mixed with dynamic chili-mayonnaise.', tags: ['Spicy'] },
    { id: 'ss12', name: 'Shrimp (Ebi)', price: '6.50+', description: 'Gently steamed and butterflied tiger shrimp.', tags: ['Classic'] },
    { id: 'ss13', name: 'Striped Bass', price: '6.50+', description: 'Exquisite, firm-textured white fish slices with a mild flavor profile.', tags: ['Traditional'] },
    { id: 'ss14', name: 'Yellowtail (Hamachi)', price: '7.50+', description: 'Premium fatty yellowtail displaying delicious sweet, buttery notes.', tags: ['Premium'] },
    { id: 'ss15', name: 'Mackerel (Saba)', price: '6.50+', description: 'Vinegar-cured oily mackerel slices providing robust, deep umami flavor.', tags: ['Traditional'] },
    { id: 'ss16', name: 'Eel (Unagi)', price: '7.50+', description: 'Perfectly baked sweet water eel fillets drenched in unagi glaze.', tags: ['Glazed'] },
    { id: 'ss17', name: 'Scallop (Hotate)', price: '8.00+', description: 'Plump ocean scallop slices, raw or slightly seared with spicy mayo.', tags: ['Exquisite'] },
    { id: 'ss18', name: 'Octopus (Tako)', price: '7.00+', description: 'Gently boiled, chewy, and rich octopus leg medallions.', tags: ['Traditional'] },
    { id: 'ss19', name: 'Flying Fish Roe (Tobiko)', price: '7.00+', description: 'Tiny, crunchy, vibrant orange fish eggs carrying a subtle ocean pop.', tags: ['Garnish'] },
    { id: 'ss20', name: 'Salmon Roe (Ikura)', price: '8.00+', description: 'Glistening, large orange gems of salmon roe delivering a rich burst of brine.', tags: ['Premium'] }
  ],
  classicrollandhandroll: [
    { id: 'cr1', name: 'Cucumber Roll (Kappa)', price: 5.50, description: 'Refreshing crisp English cucumber julienne rolls.', tags: ['Vegetarian', 'Light'] },
    { id: 'cr2', name: 'Asparagus Roll', price: 5.50, description: 'Steamed green asparagus stalks wrapped neatly with seasoned rice.', tags: ['Vegetarian'] },
    { id: 'cr3', name: 'Avocado Roll', price: 5.50, description: 'Velvety slices of rich, fully ripe Mexican Haas avocados.', tags: ['Vegetarian', 'Healthy'] },
    { id: 'cr4', name: 'Oshinko Roll', price: 5.50, description: 'Savory sweet pickled Japanese yellow radish strips.', tags: ['Vegetarian'] },
    { id: 'cr5', name: 'Peanut Avocado Roll', price: 6.00, description: 'Crunchy sweet roasted honeyed peanut chunks layered with creamy avocado.', tags: ['Unique', 'Vegetarian'] },
    { id: 'cr6', name: 'Tuna Roll', price: 6.50, description: 'A timeless rolled classic containing rich raw red tuna core.', tags: ['Sashimi Grade'] },
    { id: 'cr7', name: 'Yellowtail Scallion Roll', price: 7.00, description: 'Buttery yellowtail minced with aromatic green garden scallions.', tags: ['Bestseller'] },
    { id: 'cr8', name: 'Sweet Potato Roll', price: 6.50, description: 'Battered sweet potato tempura wrapped inside, glazed with honey eels.', tags: ['Crispy', 'Vegetarian'] },
    { id: 'cr9', name: 'Salmon Skin Roll', price: 6.50, description: 'Toasted salmon skin and cucumber slivers finished with unagi tare.', tags: ['Crispy'] },
    { id: 'cr10', name: 'Salmon Avocado Roll', price: 7.50, description: 'Perfect pair of fresh Atlantic raw salmon and ripe creamy avocado.', tags: ['Traditional'] },
    { id: 'cr11', name: 'AAC Roll', price: 6.00, description: 'Combination of fresh Avocado, Asparagus strips, and English Cucumber.', tags: ['Vegetarian'] },
    { id: 'cr12', name: 'California Roll', price: 6.50, description: 'Classic imitation crabmeat, cucumber, and avocado with roasted sesame seeds.', tags: ['Worldwide Favorite'] },
    { id: 'cr13', name: 'Eel Avocado Roll', price: 7.50, description: 'Glazed roasted freshwater unagi eel wrapped alongside avocado.', tags: ['Sweet Glaze'] },
    { id: 'cr14', name: 'Eel Cucumber Roll', price: 7.50, description: 'Sweet baked eel rolls paired with refreshing crisp cucumber slices.', tags: ['Sweet Glaze'] },
    { id: 'cr15', name: 'Spicy Salmon Roll', price: 7.50, description: 'Atlantic salmon cubes tossed with crispy tempura, scallions and spicy mayo.', tags: ['Spicy'] },
    { id: 'cr16', name: 'Spicy Tuna Roll', price: 7.50, description: 'Chopped yellowfin tuna with crunchy chili mayo paste.', tags: ['Spicy', 'Popular'] },
    { id: 'cr17', name: 'Spicy Yellowtail Roll', price: 7.50, description: 'Minced hamachi fish combined with hot sriracha mayo seasoning.', tags: ['Spicy'] },
    { id: 'cr18', name: 'Spicy Kani Roll', price: 7.00, description: 'Julienned crab meat blended with spicy sriracha and tempura flakes.', tags: ['Spicy'] },
    { id: 'cr19', name: 'Spicy Shrimp Roll', price: 7.00, description: 'Gently steamed shrimp dressed with hot chili mayonnaise.', tags: ['Spicy'] },
    { id: 'cr20', name: 'Philadelphia Roll', price: 7.50, description: 'Rich Philly cream cheese with hickory-smoked salmon salmon and avocado.', tags: ['Creamy'] },
    { id: 'cr21', name: 'Alaska Roll', price: 7.50, description: 'Fresh raw salmon, cucumber, and ripe avocado rolled together.', tags: ['Fresh'] },
    { id: 'cr22', name: 'Shrimp Tempura Roll', price: 8.50, description: 'Crisp fried shrimp tempura, cucumber, avocado, wrapped with unagi sauce.', tags: ['Crispy Bestseller'] },
    { id: 'cr23', name: 'Spider Tempura Roll', price: 10.50, description: 'Whole gold-fried crispy soft shell crab, loaded cucumber, avocado, and tobiko.', tags: ['Large Roll'] },
    { id: 'cr24', name: 'Easter Roll', price: 8.00, description: 'Steamed shrimp, egg omelet, cucumber, and avocado coated in roe.', tags: ['Hearty'] },
    { id: 'cr25', name: 'Kampyo Roll', price: 5.50, description: 'Sweetened cooked Japanese calabash melon shavings rolled classically.', tags: ['Vegetarian'] },
    { id: 'cr26', name: 'Spicy Crabstick Roll', price: 7.00, description: 'Crab stick dressed with dynamic chili paste and rolled.', tags: ['Spicy'] },
    { id: 'cr27', name: 'Spicy Scallop Roll', price: 8.50, description: 'Tender raw sea scallop cubes mixed with sriracha mayo, rolled with scallions.', tags: ['Premium', 'Spicy'] },
    { id: 'cr28', name: 'Oyster Tempura Roll', price: 9.50, description: 'Crisp battered sea oyster, green lettuce leaf, cucumber with savory unagi sauce.', tags: ['Crispy'] },
    { id: 'cr29', name: 'Futo Maki Roll', price: 7.50, description: 'Large roll incorporating crab stick, tamago egg, kampyo, avocado, and cucumber.', tags: ['Traditional'] }
  ],
  signaturerolls: [
    { id: 'sr1', name: 'Rainbow Roll', price: 14.95, description: 'California roll inside, elegantly layered with raw tuna, salmon, white fish, striped bass, and ripe avocado.', tags: ['Colorful', 'Classic'] },
    { id: 'sr2', name: 'Dragon Roll', price: 14.95, description: 'BBQ unagi and cucumber inside, draped with delicious layers of avocado and unagi sauce.', tags: ['Popular'] },
    { id: 'sr3', name: 'Jumbo Veggie Roll', price: 11.95, description: 'Avocado, cucumber, asparagus, kampyo, oshinko yellow pickle, rolled in large green soy sheets.', tags: ['Vegetarian'] },
    { id: 'sr4', name: 'Finger Lake Roll', price: 15.95, description: 'Spicy crunch tuna inside, topped with fresh salmon, yellowtail, and chef special yuzu chili glaze.', tags: ['Ithaca Local Special'] },
    { id: 'sr5', name: 'Crazy Roll', price: 14.95, description: 'Pepper tuna and avocado inside, topped with spicy tuna, crunchy flakes, and sweet unagi sauce.', tags: ['Spicy'] },
    { id: 'sr6', name: 'Buffalo Roll', price: 14.95, description: 'Shrimp tempura, cream cheese inside, topped with spicy crab sticks, dynamic mango sauce and masago.', tags: ['Bold Flavor'] },
    { id: 'sr7', name: 'Ithaca Roll', price: 14.95, description: 'Crispy fried calamari and cucumber inside, topped with baked spicy shrimp, kani and sweet soy glaze.', tags: ['Local Special'] },
    { id: 'sr8', name: 'Salmon Amazing Roll', price: 15.95, description: 'Salmon tempura, avocado inside, topped with fresh Atlantic salmon sashimi, spicy mayo, and torched finish.', tags: ['Torched'] },
    { id: 'sr9', name: 'Volcano Roll', price: 15.95, description: 'Crunchy spicy tuna and yellowtail inside, topped with a bubbling hot baked scallop-kani dynamite cream sauce.', tags: ['Bubbling Hot', 'Spicy'] },
    { id: 'sr10', name: 'Spicy Girl Roll', price: 14.95, description: 'Spicy tuna, salmon, yellowtail, cucumber inside, topped with fresh avocado, crunchies, and hot chili oil.', tags: ['Very Spicy'] },
    { id: 'sr11', name: 'Tokyo Roll', price: 16.95, description: 'Shrimp tempura, spicy lobby salad, cream cheese inside, topped with fried sweet plantain, spicy eel glaze.', tags: ['Chef Specialty'] },
    { id: 'sr12', name: 'Naruto Roll', price: 14.95, description: 'Tuna, salmon, yellowtail, kani and avocado wrapped in paper-thin cucumber sheet (no rice) with ponzu.', tags: ['Low-Carb', 'Gluten-Free'] },
    { id: 'sr13', name: 'Fantasy Roll', price: 15.95, description: 'Lobster tempura and avocado inside, topped with sliced mangoes, sweet coconut flakes, and a honey glaze.', tags: ['Sweet & Savory'] },
    { id: 'sr14', name: 'Dynamite Roll', price: 14.95, description: 'Chopped yellowtail, tuna, avocado inside, coated in masago, spicy mayonnaise, and oven-baked kani dynamic.', tags: ['Spicy'] },
    { id: 'sr15', name: 'Godzilla Roll', price: 15.95, description: 'Spicy tuna, kani, cream cheese, avocado inside, deep fried as a whole roll, drizzled with spicy unagi glaze.', tags: ['Flashed Fried'] },
    { id: 'sr16', name: 'Rock and Roll', price: 14.95, description: 'Shrimp tempura and cucumber inside, topped with baked freshwater eel, sliced avocado, and black tobiko.', tags: ['Savory'] },
    { id: 'sr17', name: 'Andy Cheung Roll', price: 16.95, description: 'Soft shell crab tempura inside, topped with baked eel, avocado, and spicy tuna crunch.', tags: ['Premium Signature'] },
    { id: 'sr18', name: 'Dancing Beef Roll', price: 16.95, description: 'Steamed asparagus and cucumber inside, topped with thin sliced USDA strip steak, torched with garlic soy sauce.', tags: ['Steak Sushi'] },
    { id: 'sr19', name: 'Sunshine Roll', price: 15.95, description: 'Crab tempura and avocado inside, topped with fresh salmon, shredded mango, kiwi dressing, and sweet chili.', tags: ['Fruity'] },
    { id: 'sr20', name: 'Tuna Amazing Roll', price: 16.95, description: 'White tuna tempura, spicy tuna inside, topped with whole seared pepper tuna, yuzu soy cream and scallions.', tags: ['Seared'] },
    { id: 'sr21', name: 'Cornell Roll', price: 15.95, description: 'Spicy salmon crunch inside, layered with orange salmon, red tuna, white tuna, avocado, and red cherry masago.', tags: ['Big Red Pride'] },
    { id: 'sr22', name: 'Golden Dragon Roll', price: 15.95, description: 'Glazed freshwater eel and avocado inside, topped with thinly-sliced super-sweet mangoes and unagi reduction.', tags: ['Sweet'] },
    { id: 'sr23', name: 'Gangnam Style Roll', price: 15.95, description: 'Crisp chicken katsu strips and cucumber inside, topped with Korean spicy bulgogi strips and scallions.', tags: ['Bold Fusion'] },
    { id: 'sr24', name: 'Manhattan Roll', price: 15.95, description: 'Shrimp tempura, cucumber inside, topped with spicy tuna, salmon, yellowtail, crunch, and gold yum-yum sauce.', tags: ['Popular'] },
    { id: 'sr25', name: 'Black Spider Roll', price: 15.95, description: 'Crispy fried soft-shell crab inside, topped with baked unagi, black fish roe, and chef house special tare.', tags: ['Premium'] },
    { id: 'sr26', name: 'Lady Lobster Roll', price: 18.95, description: 'Sautéed butter lobster tail and asparagus inside, decorated with fresh sliced salmon, avocado, gold flakes.', tags: ['Exquisite Luxury'] },
    { id: 'sr27', name: 'Sweet Valentine Roll', price: 16.95, description: 'Spicy crunchy tuna inside, beautifully shaped with sliced tuna, salmon, yuzu, wrapped in pink soy paper.', tags: ['Romantic Special'] }
  ],
  riceandnoodles: [
    { id: 'rn1', name: 'Teriyaki Fried Rice', price: 12.95, description: 'Premium calrose rice stir-fried in hot wok with sweet teriyaki, egg, onion, and peas.', tags: ['Staple'] },
    { id: 'rn2', name: 'Yaki Udon', price: 14.95, description: 'Thick, chewy Japanese wheat flour noodles pan-fried with assorted cabbage, onion, and savory soy sauce.', tags: ['Skillet Pan'] },
    { id: 'rn3', name: 'Yaki Soba', price: 14.95, description: 'Thin, buckwheat flour noodles stir-fried with vegetables and savory sweet soba sauce glaze.', tags: ['Japanese Fast Food'] },
    { id: 'rn4', name: 'Lo Mein', price: 13.95, description: 'Soft wheat flour egg noodles stir-fried with bean sprouts, onion, carrots, and house brown soy.', tags: ['Chinese Classic'] },
    { id: 'rn5', name: 'Seafood Yaki Udon', price: 18.95, description: 'Pan-fried thick udon noodles loaded with prawns, scallops, mussels and squid pieces.', tags: ['Seafood Delight'] },
    { id: 'rn6', name: 'Nabeyaki Udon', price: 16.95, description: 'Hot stone pot soup containing thick udon, chicken, egg, and a gold skewered shrimp tempura on top.', tags: ['Aesthetic Bowl'] },
    { id: 'rn7', name: 'Seafood Noodle Soup', price: 18.95, description: 'Simmering clear kelp ocean broth loaded with sea delicacies and choice of ramen/udon noodles.', tags: ['Warm Soup'] },
    { id: 'rn8', name: 'Pad Thai', price: 14.95, description: 'Pan-fried thin Thai rice noodles combined with egg, tofu, crushed roasted peanuts, fresh bean sprouts, and tangy sweet tamarind glaze.', tags: ['Nutty Thai'] },
    { id: 'rn9', name: 'Pad See-Ew', price: 14.95, description: 'Stir-fried wide-flat rice noodles cooked with local broccoli florets and dark sweet soy sauce.', tags: ['Sweet Dark Soy'] },
    { id: 'rn10', name: 'Drunken Noodles', price: 14.95, description: 'Pan-fried spicy flat broad noodles, bell pepper, sweet basil, garlic, and hot bird\'s eye chili.', tags: ['Very Spicy'] },
    { id: 'rn11', name: 'Drunken Fried Rice', price: 14.95, description: 'Savory stir-fried rice loaded with sweet basil, green chili, onion, garlic, and customized protein selection.', tags: ['Spicy'] },
    { id: 'rn12', name: 'Pad Thai Chicken', price: 15.95, description: 'Classic peanut pad thai recipe wok-tossed with sweet chicken breast strips.', tags: ['Popular'] }
  ],
  sushibarentrees: [
    { id: 'sbe1', name: 'Veggie Maki Combo', price: 15.95, description: 'Includes 1 Cucumber roll, 1 Avocado roll, and 1 Sweet Potato tempura roll.', tags: ['Vegetarian Choice'] },
    { id: 'sbe2', name: 'Maki Combo A', price: 17.95, description: 'Includes 1 Tuna roll, 1 Salmon roll, and 1 Classic California roll.', tags: ['Combo'] },
    { id: 'sbe3', name: 'Maki Combo B', price: 18.95, description: 'Includes 1 Spicy Tuna roll, 1 Spicy Salmon, and 1 Spicy Kani roll.', tags: ['Spicy Combo'] },
    { id: 'sbe4', name: 'Spicy Maki Dinner', price: 19.95, description: 'Includes 1 Spicy tuna roll, 1 Spicy salmon roll, and 1 Volcano dynamite roll.', tags: ['Spicy'] },
    { id: 'sbe5', name: 'Tempura Combo', price: 18.95, description: 'Curated sushi platter served alongside shrimp and vegetable tempura basket.', tags: ['Crispy Side'] },
    { id: 'sbe6', name: 'Unagi Don', price: 22.95, description: 'Slices of roasted, sweet-marinated unagi eel over a massive bed of steamed calrose seasoned sushi rice.', tags: ['Donburi Classic'] },
    { id: 'sbe7', name: 'Salmon Lover', price: 24.95, description: '4 pieces of raw salmon sushi, 4 raw salmon sashimi, and 1 dynamic Salmon Avocado roll.', tags: ['Salmon Fanatic'] },
    { id: 'sbe8', name: 'Chirashi', price: 24.95, description: '12 pieces of chef\'s fresh raw fish variety arranged over a classic steam-seasoned bowl.', tags: ['Traditional Bowl'] },
    { id: 'sbe9', name: 'Sushi Dinner', price: 22.95, description: '8 pieces of assorted chef-selected nigiri sushi served with 1 classic Tuna roll.', tags: ['Value Choice'] },
    { id: 'sbe10', name: 'Sashimi Dinner', price: 24.95, description: '15 slices of premium raw sashimis, expertly carved, served with a side bowl of rice.', tags: ['Raw Feast'] },
    { id: 'sbe11', name: 'Sushi and Sashimi Combo', price: 28.95, description: '5 pieces of fresh sushi, 9 pieces of premium sashimi, and 1 California roll.', tags: ['Bestseller'] },
    { id: 'sbe12', name: 'Sushi for 2', price: 49.95, description: '12 pieces of nigiri, 12 pieces of sashimi, 1 Dragon Roll, and 1 Salmon Amazing Roll.', tags: ['Date Night'] },
    { id: 'sbe13', name: 'Tokyo Boat', price: 59.95, description: 'Vast wooden boat with 16 sashimi slices, 10 sushi pieces, 1 Rainbow Roll, and 1 Spicy Girl Roll.', tags: ['Epic Feast'] },
    { id: 'sbe14', name: 'Salmon Don', price: 22.95, description: 'Atlantic salmon sashimi slices arrayed gracefully over vinegared sushi rice.', tags: ['Rice Bowl'] },
    { id: 'sbe15', name: 'Tuna Lover', price: 24.95, description: '4 pieces of tuna sushi, 4 pieces of tuna sashimi, and 1 Spicy Tuna Roll combo.', tags: ['Tuna Fanatic'] }
  ],
  kitchenentrees: [
    { id: 'ke1', name: 'Chicken Katsu', price: 16.95, description: 'Coated in crisp Japanese panko crumbs, fried golden and drizzled with sweet-tangy tonkatsu glaze.', tags: ['Crispy'] },
    { id: 'ke2', name: 'Pork Katsu (Tonkatsu)', price: 16.95, description: 'Crusted Berkshire pork cutlet, breaded with panko and fried till cracking.', tags: ['Traditional'] },
    { id: 'ke3', name: 'Vegetable Teriyaki', price: 14.95, description: 'Wok-steamed broccoli, carrots, onions, cabbage, loaded with sweet glaze.', tags: ['Vegetarian'] },
    { id: 'ke4', name: 'Vegetable Tempura', price: 13.95, description: 'Assorted sweet potato, broccoli, onion ring tempura with savory tentsuyu dip.', tags: ['Vegetarian'] },
    { id: 'ke5', name: 'Tofu Teriyaki', price: 15.95, description: 'Slabs of fried bean curd drenched with sweet savory teriyaki sauce.', tags: ['Vegetarian'] },
    { id: 'ke6', name: 'Chicken Teriyaki', price: 18.95, description: 'Pan-seared chicken breast basted in traditional Japanese teriyaki sauce.', tags: ['Diner Favorite'] },
    { id: 'ke7', name: 'Shrimp Teriyaki', price: 22.95, description: 'Succulent shrimp skillet pan-seared with sweet mirin soy glaze.', tags: ['Seafood'] },
    { id: 'ke8', name: 'Steak Teriyaki', price: 24.95, description: 'Seared tender USDA beef strips glazed in deep aromatic teriyaki sauce.', tags: ['Beef Lover'] },
    { id: 'ke9', name: 'Salmon Teriyaki', price: 23.95, description: 'Atlantic salmon fillet pan-grilled skin-on, coated with sweet glaze.', tags: ['Seafood'] },
    { id: 'ke10', name: 'Shrimp and Vegetable Tempura', price: 21.95, description: 'Lightly battered shrimp paired with assorted golden fried garden vegetables.', tags: ['Classic'] },
    { id: 'ke11', name: 'Duck Teriyaki', price: 25.95, description: 'Roasted and sliced crispy duck breast paired with deep sweet teriyaki glaze.', tags: ['Exquisite'] },
    { id: 'ke12', name: 'Short Ribs Teriyaki', price: 26.95, description: 'Sizzling Korean-style crosscut galbi short ribs glazed in teriyaki reduction.', tags: ['Rich Flavor'] },
    { id: 'ke13', name: 'Sesame Chicken', price: 16.95, description: 'Crisp chicken nuggets tossed with sweet dark glaze and roasted white sesame seeds.', tags: ['Crowd Pleaser'] },
    { id: 'ke14', name: 'Sweet and Sour Chicken', price: 15.95, description: 'Flashed chicken cubes, pineapple, bell pepper in a sweet-and-sour glaze.', tags: ['Sweet & Tangy'] },
    { id: 'ke15', name: 'Chicken with Black Bean Sauce', price: 16.95, description: 'Stir-fried sweet chicken breast cubes in fully fermented, savory douchi black bean sauce.', tags: ['Chinese Fusion'] },
    { id: 'ke16', name: 'Chicken with Mixed Vegetables', price: 16.95, description: 'Lean chicken sautéed with broccoli florets, snow peas, mushrooms, celery, and clean white sauce.', tags: ['Healthy Choice'] },
    { id: 'ke17', name: 'Spicy Garlic Chicken', price: 16.95, description: 'Chicken strips in bold sweet-spicy roasted garlic oil paste.', tags: ['Spicy'] },
    { id: 'ke18', name: 'Beef with Black Bean Sauce', price: 19.95, description: 'Silky sliced beef steak sautéed with peppers in rich garlic black bean broth.', tags: ['Fusion'] },
    { id: 'ke19', name: 'Beef with Mixed Vegetables', price: 19.95, description: 'Tender beef strips in rich glaze with stir-fried market seasonal greens.', tags: ['Classic'] },
    { id: 'ke20', name: 'Spicy Garlic Beef', price: 19.95, description: 'Sliced tender beef toss-fried with brown bamboo shoots in spicy garlic.', tags: ['Spicy'] },
    { id: 'ke21', name: 'Mongolian Beef', price: 19.95, description: 'Stir-fried beef in hot wok with sweet scallions, yellow onions, and soy reduction.', tags: ['Local Bestseller'] },
    { id: 'ke22', name: 'Shrimp with Black Bean Sauce', price: 21.95, description: 'Giant shrimp sautéed with bell pepper and white onions in Cantonese style black bean paste.', tags: ['Seafood'] },
    { id: 'ke23', name: 'Shrimp with Mixed Vegetables', price: 21.95, description: 'Colossal shrimp sautéed with fresh crisp baby bok choy and baby corn.', tags: ['Healthy'] },
    { id: 'ke24', name: 'Spicy Garlic Shrimp', price: 21.95, description: 'Sizzling peeled shrimp cooked in fragrant dark garlic and chili paste sauce.', tags: ['Spicy'] },
    { id: 'ke25', name: 'Seafood Delight', price: 26.95, description: 'Pristine scallops, sea shrimp, calamari, mussels, crab sticks in a clear, delicious white garlic reduction.', tags: ['Premium Seafood'] },
    { id: 'ke26', name: 'Thai Spicy Basil Chicken', price: 16.95, description: 'Lean minced chicken cooked in a scorching wok with Thai holy basil, red chilis, garlic, and oyster soy.', tags: ['Spicy Thai'] },
    { id: 'ke27', name: 'Thai Basil Beef', price: 19.95, description: 'Marinated beef slices cooked with spicy Thai bird\'s eyes, sweet onions, and crisp basil leaf.', tags: ['Spicy'] },
    { id: 'ke28', name: 'Thai Basil Shrimp', price: 21.95, description: 'Fresh pan-toss shrimp blended with dynamic sweet basil paste.', tags: ['Spicy'] },
    { id: 'ke29', name: 'Crispy Tofu Black Bean Sauce', price: 14.95, description: 'Gold fried silken bean curd cubes draped in intense savory black bean sauce.', tags: ['Vegetarian'] },
    { id: 'ke30', name: 'Panang Curry', price: 16.95, description: 'Creamy peanut-infused aromatic Thai curry, bell pepper, and kaffir lime leaves.', tags: ['Mild Heat'] },
    { id: 'ke31', name: 'Panang Curry Tofu', price: 15.95, description: 'Peanut curry base filled with fried bean curd squares.', tags: ['Vegetarian'] },
    { id: 'ke32', name: 'Panang Curry Shrimp', price: 21.95, description: 'Peanut coconut curry simmered with ocean-fresh peeled tiger prawns.', tags: ['Premium'] },
    { id: 'ke33', name: 'Green Curry', price: 16.95, description: 'Fiery young Thai green chili paste, creamy coconut milk, fresh eggplant, bamboo stems, and sweet basil leaves.', tags: ['Spicy Thai'] },
    { id: 'ke34', name: 'Green Curry Beef', price: 19.95, description: 'USDA Choice beef tender medallions simmered in hot green curry stock.', tags: ['Spicy'] },
    { id: 'ke35', name: 'Green Curry Shrimp', price: 21.95, description: 'Tiger prawns stewed in delicious green coconut cream.', tags: ['Spicy'] }
  ],
  hibachidinners: [
    { id: 'hb1', name: 'Hibachi Tofu and Vegetable', price: 18.95, description: 'Seared tofu steaks and garden vegetables grilled on flat-top griddle with sesame oil.', tags: ['Vegetarian'] },
    { id: 'hb2', name: 'Hibachi Chicken', price: 22.95, description: 'Plump premium chicken breast fillet grilled with garlic butter and finished with splash cooking sake.', tags: ['Patron Favorite'] },
    { id: 'hb3', name: 'Hibachi NY Strip Steak', price: 28.95, description: 'Aromatic seared New York strip steak diced and cooked to preferred temperature with soy base dressing.', tags: ['A-Grade Meat'] },
    { id: 'hb4', name: 'Hibachi Shrimp', price: 26.95, description: 'Pristine ocean desk shrimp flambéed with garlic and squeeze of fresh lemon.', tags: ['Crowd Favorite'] },
    { id: 'hb5', name: 'Hibachi Squid', price: 25.95, description: 'Flashed calamari tubes cooked under pressure with rich sweet teriyaki sauce.', tags: ['Aesthetic'] },
    { id: 'hb6', name: 'Hibachi Salmon', price: 27.95, description: 'Sashimi-grade salmon filet seared perfectly with skin crisping.', tags: ['Seafood Supreme'] },
    { id: 'hb7', name: 'Hibachi Swordfish', price: 29.95, description: 'Premium swordfish cutlet grilled with lemon-soy glaze.', tags: ['Exclusive Item'] },
    { id: 'hb8', name: 'Hibachi Scallop', price: 31.95, description: 'Fat cold-water sea scallops seared under golden color, retaining moisture.', tags: ['Top Grade'] },
    { id: 'hb9', name: 'Hibachi Filet Mignon', price: 34.95, description: 'Prestige USDA Choice beef tenderloin cubes cooked on flat griddle, melting buttery texture.', tags: ['Elite Specialty'] },
    { id: 'hb10', name: 'Hibachi Twin Lobster Tails', price: 43.95, description: 'Two cold-water sweet lobster tails seared with garlic butter, sake, and premium herbs.', tags: ['Luxurious Plates'] },
    { id: 'hb11', name: 'Chicken and Shrimp Hibachi Combination', price: 29.95, description: 'Duo of garlic butter seared chicken cubes and colossal tiger shrimp.', tags: ['Value Combination'] },
    { id: 'hb12', name: 'Chicken and Salmon Hibachi Combination', price: 29.95, description: 'Plump chicken tenderloins and Atlantic ocean seared salmon.', tags: ['Popular Combo'] },
    { id: 'hb13', name: 'Steak and Chicken Hibachi Combination', price: 31.95, description: 'Succulent NY strip steak cubes paired with grilled garlic chicken.', tags: ['Diner Favorite'] },
    { id: 'hb14', name: 'Steak and Salmon Hibachi Combination', price: 32.95, description: 'Tasty bite steak paired with skin-seared salmon medallion.', tags: ['Classic Land & Sea'] },
    { id: 'hb15', name: 'Shrimp and Steak Hibachi Combination', price: 32.95, description: 'Bestseller combining USDA Choice strip steak block and colossal tiger prawns.', tags: ['Bestseller Combo'] },
    { id: 'hb16', name: 'Shrimp and Scallop Hibachi Combination', price: 33.95, description: 'Colossal shrimp seared alongside ocean sweet sea scallops.', tags: ['Seafood Extravaganza'] },
    { id: 'hb17', name: 'Scallop and Steak Hibachi Combination', price: 34.95, description: 'NY strip steak cubes and large whole sweet scallops.', tags: ['Premium Combo'] },
    { id: 'hb18', name: 'Filet Mignon and Chicken Combination', price: 34.95, description: 'Buttery melt center-cut fillet mignon and sweet golden chicken breasts.', tags: ['Luxury Duo'] },
    { id: 'hb19', name: 'Filet Mignon and Shrimp Combination', price: 35.95, description: 'Rich beef tenderloin cubes matched with juicy seared ocean shrimp.', tags: ['Chef Recommended'] },
    { id: 'hb20', name: 'Filet Mignon and Scallop Combination', price: 37.95, description: 'Melt-in-mouth beef fillet mignon accompanied with gold crusted scallops.', tags: ['Exquisite'] },
    { id: 'hb21', name: 'Lobster and Chicken Combination', price: 36.95, description: 'Cold-water sweet lobster tail and tender garlic herb chicken.', tags: ['Special Combination'] },
    { id: 'hb22', name: 'Lobster and Steak Combination', price: 38.95, description: 'One full lobster tail seared with garlic butter paired with NY strip steak.', tags: ['Premium Combo'] },
    { id: 'hb23', name: 'Lobster and Shrimp Combination', price: 38.95, description: 'Mouthwatering lobster tail seared with massive giant tiger shrimp.', tags: ['Full Plate'] },
    { id: 'hb24', name: 'Lobster and Scallop Combination', price: 39.95, description: 'Cold water lobster tail coupled with sweet ocean sea scallops.', tags: ['Royal Feast'] },
    { id: 'hb25', name: 'Lobster and Filet Mignon Combination', price: 41.95, description: 'Sizzling sweet lobster tail alongside choice center-cut beef tenderloin.', tags: ['Ultimate Luxury'] },
    { id: 'hb26', name: 'Seafood Deluxe Hibachi Combination', price: 44.95, description: 'The absolute royal trio of lobster tail, sea scallops, and giant prawns.', tags: ['The Legend Plate'] },
    { id: 'hb27', name: 'Tokyo Land and Sea Hibachi Combination', price: 38.95, description: 'Chef selected trio of juicy chicken breast, strip steak cubes, and ocean prawns.', tags: ['Most Popular'] }
  ],
  drinks: [
    { id: 'dk1', name: 'Thai Iced Tea', price: 4.50, description: 'Rich, sweetened black tea brewed with spices and finished with creamy milk float over ice.', tags: ['Creamy', 'Traditional'] },
    { id: 'dk2', name: 'Thai Iced Coffee', price: 4.50, description: 'Brewed robust dark coffee sweetened and topped with condensed cream float.', tags: ['Sweet Coffee'] },
    { id: 'dk3', name: 'Japanese Soda (Ramune)', price: 3.95, description: 'Glass bottle carbonated liquid fun sealed with marble. Choice of Strawberry, Melon, Lychee.', tags: ['Imported', 'Kids Favorite'] },
    { id: 'dk4', name: 'Canned Soda', price: 2.00, description: 'Classic selection of Coca-Cola, Diet Coke, Sprite, or Ginger Ale.', tags: ['Zero Sugar Option'] },
    { id: 'dk5', name: 'Sparkling Water', price: 3.00, description: 'Premium carbonated sparkling mineral water.', tags: ['Crisp'] },
    { id: 'dk6', name: 'Bottled Water', price: 2.00, description: 'Purified alpine mineral spring bottled water.', tags: ['Pure'] }
  ],
  dessert: [
    { id: 'ds1', name: 'Banana Tempura', price: 6.50, description: 'Fully ripe bananas tempura battered, deep fried warm, and glazed with dynamic pure honey syrup.', tags: ['Hot Dessert'] },
    { id: 'ds2', name: 'Tempura Cheesecake', price: 7.95, description: 'Deep fried vanilla cheesecake in crispy light tempura crust, topped with dark chocolate drizzle.', tags: ['Heavenly Sweet'] }
  ]
};
